### PR TITLE
Making the table not extend past the container

### PR DESCRIPTION
**Pull request by JaceBayless**
This is for issue #856 on CPPR

scrolling

### CODE REVIEW

**Review by willtcarey — APPROVED** [review]
Looks good. Do we need to bump the version so we can update it over in the institute?

**Comment by JaceBayless** [comment]
I think so, I think we probably want to bump the version and release the new version so we can update that project.

**Comment by JaceBayless** [comment]
Is there anything other than this that I need to do to bump the version?

**Review by willtcarey — APPROVED** [review]
This looks good for bumping the version. I think we have to run something to release the version then.

**Pull request merged**
